// <auto-generated />
using Cqrs.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cqrs.Migrations
{
    [DbContext(typeof(StudentContext))]
    [Migration("20241019200240_initialcreate")]
    partial class initialcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.35");

            modelBuilder.Entity("Cqrs.Data.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 25,
                            Name = "Ferhat",
                            Number = 1
                        },
                        new
                        {
                            Id = 2,
                            Age = 25,
                            Name = "Betül",
                            Number = 2
                        },
                        new
                        {
                            Id = 3,
                            Age = 31,
                            Name = "Osman",
                            Number = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
